#!/bin/bash

#
# Runs on creation of a new instance and sets up the build environment
#
# Called by the new-instance script
# 
# See http://alestic.com/2009/06/ec2-user-data-scripts

set -e -x
export DEBIAN_FRONTEND=noninteractive
export LOG=/tmp/install.log
export APT_INSTALL="sudo apt-get install -y"
export TEE="tee -a"
export INSTALL_DIR=/tmp
export WGET=/usr/bin/wget
export RAKE_FILE=http://github.com/minch/ec2onrails/raw/master/server/rakefile.rb
export RAKE="/usr/bin/rake --trace"

export MESSAGE="user-data-script:  begin"
echo $MESSAGE | $TEE $LOG

# Install ruby
if [ ! `which ruby` ]; then
  echo "Installing ruby..."
  $APT_INSTALL ruby | $TEE $LOG
fi

# Install rake
if [ ! `which rake` ]; then
  echo "Installing rake..."
  $APT_INSTALL rake | $TEE $LOG
fi

cd $INSTALL_DIR
# cmd = "get the rake file"
$WGET $RAKE_FILE

# TODO:
echo "run the rake file"
$RAKE | $TEE $LOG

MESSAGE="user-data-script:  end"
echo $MESSAGE | $TEE $LOG

