#!/bin/bash

#
# Runs on creation of a new instance and sets up the build environment
#
# Called by the new-instance script
# 
# See http://alestic.com/2009/06/ec2-user-data-scripts

set -e -x
export DEBIAN_FRONTEND=noninteractive

echo "Running the user-data-script build..."

# Install ruby
if ![ `which ruby` ]; then
  echo "Installing ruby..."
  system "sudo apt-get install rake | tee /tmp/install-ruby.log"
fi

# Install rake

if ![ `which rake` ]; then
  echo "Installing rake..."
  system "sudo apt-get install rake | tee /tmp/install-rake.log"
fi

# TODO:
# cmd = "get the rake file"
# cmd = "run the rake file"

